<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:tns="Unity.Multiplayer.Center.Editor" elementFormDefault="qualified" targetNamespace="Unity.Multiplayer.Center.Editor" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:import schemaLocation="UnityEngine.UIElements.xsd" namespace="UnityEngine.UIElements" />
  <xs:complexType name="RecommendationsGridType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q1="UnityEngine.UIElements" base="q1:VisualElementType">
        <xs:choice />
        <xs:attribute name="item-template" type="xs:string" />
        <xs:attribute name="recommendations" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="RecommendationsGrid" xmlns:q2="UnityEngine.UIElements" substitutionGroup="q2:VisualElement" type="tns:RecommendationsGridType" />
  <xs:complexType name="HelpIconType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q3="UnityEngine.UIElements" base="q3:VisualElementType">
        <xs:choice />
        <xs:attribute name="documentation-url" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="HelpIcon" xmlns:q4="UnityEngine.UIElements" substitutionGroup="q4:VisualElement" type="tns:HelpIconType" />
  <xs:complexType name="QuestionModeSwitcherType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q5="UnityEngine.UIElements" base="q5:VisualElementType">
        <xs:choice />
        <xs:attribute default="false" name="question-mode" type="xs:boolean" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="QuestionModeSwitcher" xmlns:q6="UnityEngine.UIElements" substitutionGroup="q6:VisualElement" type="tns:QuestionModeSwitcherType" />
  <xs:complexType name="ImageWithPlaceholderElementType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q7="UnityEngine.UIElements" base="q7:ImageType">
        <xs:choice />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="ImageWithPlaceholderElement" xmlns:q8="UnityEngine.UIElements" substitutionGroup="q8:Image" type="tns:ImageWithPlaceholderElementType" />
  <xs:complexType name="PackageItemType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q9="UnityEngine.UIElements" base="q9:VisualElementType">
        <xs:choice />
        <xs:attribute name="package-id" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="PackageItem" xmlns:q10="UnityEngine.UIElements" substitutionGroup="q10:VisualElement" type="tns:PackageItemType" />
  <xs:complexType name="PackageIconType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q11="UnityEngine.UIElements" base="q11:VisualElementType">
        <xs:choice />
        <xs:attribute name="package-id" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="PackageIcon" xmlns:q12="UnityEngine.UIElements" substitutionGroup="q12:VisualElement" type="tns:PackageIconType" />
  <xs:complexType name="DelayedPackageDescriptionBindingType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element xmlns:q13="UnityEngine.UIElements" ref="q13:VisualElement" />
    </xs:choice>
    <xs:attribute name="property" type="xs:string" />
    <xs:attribute default="WhenDirty" name="update-trigger" xmlns:q14="UnityEngine.UIElements" type="q14:BindingUpdateTriggerType" />
    <xs:anyAttribute processContents="lax" />
  </xs:complexType>
  <xs:element name="DelayedPackageDescriptionBinding" type="tns:DelayedPackageDescriptionBindingType" />
  <xs:complexType name="DelayedPackageDocumentationBindingType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element xmlns:q15="UnityEngine.UIElements" ref="q15:VisualElement" />
    </xs:choice>
    <xs:attribute name="property" type="xs:string" />
    <xs:attribute default="WhenDirty" name="update-trigger" xmlns:q16="UnityEngine.UIElements" type="q16:BindingUpdateTriggerType" />
    <xs:anyAttribute processContents="lax" />
  </xs:complexType>
  <xs:element name="DelayedPackageDocumentationBinding" type="tns:DelayedPackageDocumentationBindingType" />
  <xs:complexType name="CategoriesContainerType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q17="UnityEngine.UIElements" base="q17:ScrollViewType">
        <xs:choice />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="CategoriesContainer" xmlns:q18="UnityEngine.UIElements" substitutionGroup="q18:ScrollView" type="tns:CategoriesContainerType" />
  <xs:complexType name="ColoredMinMaxSliderType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q19="UnityEngine.UIElements" base="q19:MinMaxSliderType">
        <xs:choice />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="ColoredMinMaxSlider" xmlns:q20="UnityEngine.UIElements" substitutionGroup="q20:MinMaxSlider" type="tns:ColoredMinMaxSliderType" />
  <xs:complexType name="HyperLinkType">
    <xs:complexContent mixed="false">
      <xs:extension xmlns:q21="UnityEngine.UIElements" base="q21:LabelType">
        <xs:choice />
        <xs:attribute name="u-r-l" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="HyperLink" xmlns:q22="UnityEngine.UIElements" substitutionGroup="q22:Label" type="tns:HyperLinkType" />
  <xs:complexType name="PackageInfoBindingType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element xmlns:q23="UnityEngine.UIElements" ref="q23:VisualElement" />
    </xs:choice>
    <xs:attribute name="property" type="xs:string" />
    <xs:attribute default="WhenDirty" name="update-trigger" xmlns:q24="UnityEngine.UIElements" type="q24:BindingUpdateTriggerType" />
    <xs:anyAttribute processContents="lax" />
  </xs:complexType>
  <xs:element name="PackageInfoBinding" type="tns:PackageInfoBindingType" />
  <xs:complexType name="DelayedPackageNameBindingType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element xmlns:q25="UnityEngine.UIElements" ref="q25:VisualElement" />
    </xs:choice>
    <xs:attribute name="property" type="xs:string" />
    <xs:attribute default="WhenDirty" name="update-trigger" xmlns:q26="UnityEngine.UIElements" type="q26:BindingUpdateTriggerType" />
    <xs:anyAttribute processContents="lax" />
  </xs:complexType>
  <xs:element name="DelayedPackageNameBinding" type="tns:DelayedPackageNameBindingType" />
  <xs:complexType name="DelayedPackageIdBindingType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element xmlns:q27="UnityEngine.UIElements" ref="q27:VisualElement" />
    </xs:choice>
    <xs:attribute name="property" type="xs:string" />
    <xs:attribute default="WhenDirty" name="update-trigger" xmlns:q28="UnityEngine.UIElements" type="q28:BindingUpdateTriggerType" />
    <xs:anyAttribute processContents="lax" />
  </xs:complexType>
  <xs:element name="DelayedPackageIdBinding" type="tns:DelayedPackageIdBindingType" />
</xs:schema>